// Reclaim Phase 4 W1 — Medical Expense Record generator.
//
// Named "Substantiation Record" until 2026-09-06; see drawCover for why it is
// now titled for what it proves rather than for the jargon of proving it. The
// module, the table (substantiation_records) and the record number (RCM-YYYY-
// NNNN) keep their names -- the number is printed on every copy a user has
// already downloaded, and the table is internal.
//
// Produces the document the brief §7 calls "the product's most valuable and
// defensible output." Two formats:
//   - IRS PDF (primary): cover page + per-expense detail page with embedded
//     receipt image and the user's confirmation timestamp (the moat).
//   - CSV: one row per expense, machine-readable.
//
// Design notes:
//   - Generation runs client-side. The PDF is downloaded directly to the
//     user; no PHI-laden artifact is persisted server-side. The DB tracks
//     that a record was generated and the user can regenerate any time.
//   - All field values are SNAPSHOTS (substantiation_record_items) — so
//     even if the underlying invoice is edited or deleted later, the record
//     continues to cite the values that existed at confirmation time.
//   - The defensibility statement on the cover page is the brand voice for
//     auditor-facing communication. Update with care.

import jsPDF from "jspdf";
import { supabase } from "@/integrations/supabase/client";
import { logError } from "@/utils/errorHandler";
import { custodianSubmissionInstructions } from "@/lib/custodianInstructions";
import { formatCurrency } from "@/lib/utils";
import {
  ATTESTATION_STATEMENT,
  documentLabel,
  type SubstantiationExpenseInput,
  type SubstantiationHeader,
} from "@/lib/claimTypes";

// The claim's data shapes live in claimTypes.ts, which is free of Supabase and
// jsPDF so the packet builder can be tested on its own. Re-exported here
// because this module is the established import site for them.
export {
  ATTESTATION_STATEMENT,
  DOCUMENT_TYPE_LABELS,
  documentLabel,
  orderForPacket,
  type ClaimDocument,
  type SubstantiationExpenseInput,
  type SubstantiationHeader,
} from "@/lib/claimTypes";

const DEFENSIBILITY_STATEMENT =
  "This record was generated by Reclaim. Each expense listed was personally confirmed eligible by the account holder on the confirmation timestamp shown. These contemporaneous timestamps serve as the account holder's substantiation under IRC §213(d) and HSA distribution record-keeping requirements (IRS Pub 969).";

const IMAGE_MIME_RX = /^image\/(png|jpeg|jpg|webp)$/i;

// ── Helpers ──────────────────────────────────────────────────────────────

function fmtDateLong(iso: string): string {
  const d = new Date(iso.length === 10 ? iso + "T00:00:00" : iso);
  return d.toLocaleDateString(undefined, {
    year: "numeric",
    month: "long",
    day: "numeric",
  });
}

function fmtTimestamp(iso: string): string {
  const d = new Date(iso);
  return (
    d.toLocaleDateString(undefined, {
      year: "numeric",
      month: "short",
      day: "numeric",
    }) +
    " at " +
    d.toLocaleTimeString(undefined, {
      hour: "2-digit",
      minute: "2-digit",
      timeZoneName: "short",
    })
  );
}

// Was a module-private `toLocaleString` call, which throws on a null amount.
// Output is byte-identical to the canonical formatter -- verified across zero,
// rounding boundaries, negatives and seven figures -- so the generated record
// is unchanged.
const fmtMoney = formatCurrency;

/**
 * Download one document from the receipts bucket.
 *
 * Signed per file, immediately before the fetch, so a long packet build can
 * never outlive its own URLs. Returns null rather than throwing: one
 * unreachable file must not sink a whole claim, and both callers report the
 * omission rather than passing over it.
 */
export async function fetchReceiptBlob(path: string): Promise<Blob | null> {
  try {
    const { data, error } = await supabase.storage
      .from("receipts")
      .createSignedUrl(path, 600);
    if (error || !data?.signedUrl) return null;
    const resp = await fetch(data.signedUrl);
    if (!resp.ok) return null;
    return await resp.blob();
  } catch (err) {
    logError("substantiationRecord: fetchReceiptBlob", err);
    return null;
  }
}

async function fetchReceiptAsDataUrl(
  path: string,
): Promise<{ dataUrl: string; mime: string } | null> {
  try {
    const blob = await fetchReceiptBlob(path);
    if (!blob) return null;
    const mime = blob.type || "application/octet-stream";
    if (!IMAGE_MIME_RX.test(mime)) {
      // Non-image (PDF, etc.) — we don't embed; the cover note explains.
      return null;
    }
    const dataUrl: string = await new Promise((resolve, reject) => {
      const reader = new FileReader();
      reader.onload = () => resolve(reader.result as string);
      reader.onerror = reject;
      reader.readAsDataURL(blob);
    });
    return { dataUrl, mime };
  } catch (err) {
    logError("substantiationRecord: fetchReceiptAsDataUrl", err);
    return null;
  }
}

function imageFormatForJsPdf(mime: string): "PNG" | "JPEG" | "WEBP" {
  const m = mime.toLowerCase();
  if (m.includes("png")) return "PNG";
  if (m.includes("webp")) return "WEBP";
  return "JPEG";
}

// ── Cover page ───────────────────────────────────────────────────────────

function drawCover(doc: jsPDF, header: SubstantiationHeader) {
  const pageW = doc.internal.pageSize.getWidth();
  const margin = 56; // ~3/4 inch

  // Title in plain English, subtitle in the technical register (2026-09-06).
  //
  // Two audiences read this page and they do not share a vocabulary. The person
  // holding it, and the custodian's phone rep they hand it to, may not be able
  // to define "substantiation"; a tax preparer or an examiner wants exactly
  // that word. Naming the document for what it PROVES rather than for what the
  // holder plans to do with it also keeps it true at every stage: nothing has
  // been reimbursed at the moment it is generated, and a shoebox-strategy
  // holder may not reimburse for twenty years -- but they need this PDF every
  // one of those years, and a title that names the step they are skipping tells
  // them it is not for them.
  //
  // "Generated by Reclaim" gave up this line: the defensibility statement lower
  // on the page opens with the same fact, and the identification block already
  // carries the generation timestamp.
  doc.setFont("helvetica", "bold");
  doc.setFontSize(22);
  doc.text("Medical Expense Record", margin, 96);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(110);
  doc.text(
    `Substantiation for HSA distributions · Tax year ${header.taxYear} · ${header.recordNumber}`,
    margin,
    116,
  );
  doc.setTextColor(0);

  // Identification block
  let y = 168;
  const left = margin;
  const labelW = 150;
  const lineGap = 22;

  const writeRow = (label: string, value: string) => {
    doc.setFont("helvetica", "bold");
    doc.setFontSize(10);
    doc.setTextColor(110);
    doc.text(label, left, y);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(11);
    doc.setTextColor(0);
    doc.text(value, left + labelW, y);
    y += lineGap;
  };

  writeRow("Record number", header.recordNumber);
  writeRow("Tax year", String(header.taxYear));
  writeRow("Generated", fmtTimestamp(header.generatedAt));
  writeRow("Account holder", header.userName);
  if (header.custodian) writeRow("HSA custodian", header.custodian);
  writeRow(
    "Expenses included",
    `${header.expenseCount} ${header.expenseCount === 1 ? "expense" : "expenses"}`,
  );
  writeRow("Total amount", fmtMoney(header.totalAmount));

  // ── Blocks ─────────────────────────────────────────────────────────────
  // A heading and a wrapped paragraph, measured so the two blocks below can't
  // run into the defensibility footer.
  const block = (heading: string, body: string) => {
    y += 14;
    doc.setFont("helvetica", "bold");
    doc.setFontSize(9);
    doc.setTextColor(110);
    doc.text(heading, left, y);
    doc.setTextColor(0);
    y += 15;
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9.5);
    const lines = doc.splitTextToSize(body, pageW - margin * 2);
    doc.text(lines, left, y);
    y += lines.length * 13;
  };

  // Workstream E3 / spec Gate 4. Only printed when the user actually ticked
  // it. Records generated before the checkbox existed simply do not carry an
  // attestation, and asserting one on their behalf would be a fabrication.
  if (header.attestedNoDoubleBenefit) {
    block(
      "ATTESTATION — NO DOUBLE BENEFIT",
      ATTESTATION_STATEMENT +
        (header.attestedAt
          ? ` Confirmed ${fmtTimestamp(header.attestedAt)}.`
          : ""),
    );
  }

  block(
    "HOW TO SUBMIT THIS CLAIM",
    custodianSubmissionInstructions(header.custodian),
  );

  // Defensibility footer
  y = doc.internal.pageSize.getHeight() - 140;
  doc.setDrawColor(220);
  doc.line(margin, y, pageW - margin, y);
  y += 24;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(80);
  const wrapped = doc.splitTextToSize(
    DEFENSIBILITY_STATEMENT,
    pageW - margin * 2,
  );
  doc.text(wrapped, margin, y);
}

// ── Per-expense page ─────────────────────────────────────────────────────

async function drawExpensePage(
  doc: jsPDF,
  index: number,
  total: number,
  expense: SubstantiationExpenseInput,
) {
  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();
  const margin = 56;

  // Page header
  doc.setFont("helvetica", "bold");
  doc.setFontSize(14);
  doc.text(`Expense ${index} of ${total}`, margin, 64);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(110);
  doc.text(expense.vendor, pageW - margin, 64, { align: "right" });
  doc.setTextColor(0);

  // Metadata block
  let y = 100;
  const labelW = 200;
  const lineGap = 18;

  const row = (label: string, value: string, mono = false) => {
    doc.setFont("helvetica", "bold");
    doc.setFontSize(9);
    doc.setTextColor(110);
    doc.text(label, margin, y);
    doc.setFont(mono ? "courier" : "helvetica", "normal");
    doc.setFontSize(10);
    doc.setTextColor(0);
    const wrapped = doc.splitTextToSize(value, pageW - margin - labelW);
    doc.text(wrapped, margin + labelW, y);
    y += Math.max(lineGap, wrapped.length * 13);
  };

  row("Patient", expense.patientName ?? "Self");
  row("Date of service", fmtDateLong(expense.date));
  row("Provider / Vendor", expense.vendor);
  row("Category", expense.category ?? "(uncategorized)");
  row("Amount", fmtMoney(expense.amount));
  row(
    "IRS Pub 502 basis",
    expense.ruleName
      ? `${expense.ruleName}${expense.ruleSectionRef ? ` — ${expense.ruleSectionRef}` : ""}`
      : "(unclassified — review required)",
  );
  row(
    "Reclaim confirmation timestamp",
    fmtTimestamp(expense.confirmedAt),
    true,
  );

  // Documents
  y += 12;
  doc.setDrawColor(220);
  doc.line(margin, y, pageW - margin, y);
  y += 18;

  const note = (text: string) => {
    doc.setFont("helvetica", "italic");
    doc.setFontSize(9);
    doc.setTextColor(140);
    const lines = doc.splitTextToSize(text, pageW - margin * 2);
    doc.text(lines, margin, y);
    doc.setTextColor(0);
    y += lines.length * 12 + 2;
  };

  doc.setFont("helvetica", "bold");
  doc.setFontSize(9);
  doc.setTextColor(110);
  doc.text(
    expense.documents.length === 0
      ? "SUPPORTING DOCUMENTS"
      : `SUPPORTING DOCUMENTS (${expense.documents.length})`,
    margin,
    y,
  );
  doc.setTextColor(0);
  y += 14;

  if (expense.documents.length === 0) {
    // Workstream E3: two different facts, and they must not read the same.
    // Medical mileage carries no third-party document by design — it is
    // substantiated by the trip recorded in Reclaim — while an expense whose
    // documentation is incomplete genuinely still needs paperwork. Telling a
    // custodian the first is the second invites a rejection that is not real.
    if (expense.documentationState === "complete") {
      note(
        "No third-party document applies to this expense. It is substantiated by the details recorded in Reclaim and shown above.",
      );
    } else {
      note("No supporting document attached — this expense still needs one.");
    }
    return;
  }

  // Embed up to 2 document images per expense to keep file size reasonable;
  // extras get a note. Non-image documents (PDFs) can't be embedded as raster,
  // and are named here instead — the ZIP claim packet carries every file in
  // full, whatever its format.
  const MAX_EMBED = 2;
  let embedded = 0;
  for (const document of expense.documents) {
    if (embedded >= MAX_EMBED) {
      note(
        `${expense.documents.length - embedded} further document(s) included in the claim packet.`,
      );
      break;
    }
    const fetched = await fetchReceiptAsDataUrl(document.path);
    if (!fetched) {
      note(
        `${documentLabel(document)} — included in the claim packet in its original format.`,
      );
      continue;
    }
    doc.setFont("helvetica", "bold");
    doc.setFontSize(8.5);
    doc.setTextColor(110);
    doc.text(documentLabel(document).toUpperCase(), margin, y);
    doc.setTextColor(0);
    y += 12;
    const maxW = pageW - margin * 2;
    const remainingH = pageH - margin - y;
    const targetW = Math.min(maxW, 360);
    const targetH = Math.min(remainingH - 24, 420);
    try {
      doc.addImage(
        fetched.dataUrl,
        imageFormatForJsPdf(fetched.mime),
        margin,
        y,
        targetW,
        targetH,
        undefined,
        "FAST",
      );
      y += targetH + 16;
      embedded++;
    } catch (err) {
      logError("substantiationRecord: addImage", err);
      note(
        "This document could not be rendered here. The original is included in the claim packet.",
      );
    }
  }
}

// ── Public PDF builder ───────────────────────────────────────────────────

export async function generateSubstantiationRecordPDF(
  header: SubstantiationHeader,
  expenses: SubstantiationExpenseInput[],
): Promise<Blob> {
  const doc = new jsPDF({
    unit: "pt",
    format: "letter",
    orientation: "portrait",
  });

  drawCover(doc, header);

  for (let i = 0; i < expenses.length; i++) {
    doc.addPage();
    // eslint-disable-next-line no-await-in-loop -- sequential by design (preserves page order)
    await drawExpensePage(doc, i + 1, expenses.length, expenses[i]);
  }

  return doc.output("blob");
}

// ── CSV builder ──────────────────────────────────────────────────────────

function csvEscape(value: string): string {
  if (/[",\n\r]/.test(value)) {
    return `"${value.replace(/"/g, '""')}"`;
  }
  return value;
}

export function generateSubstantiationRecordCSV(
  header: SubstantiationHeader,
  expenses: SubstantiationExpenseInput[],
): string {
  const rows: string[] = [];
  rows.push(
    `# Reclaim Medical Expense Record ${header.recordNumber} — Tax Year ${header.taxYear}`,
  );
  rows.push(`# Generated ${fmtTimestamp(header.generatedAt)}`);
  rows.push(
    `# Account holder: ${header.userName} — ${header.expenseCount} expenses, ${fmtMoney(header.totalAmount)} total`,
  );
  if (header.custodian) rows.push(`# Custodian: ${header.custodian}`);
  if (header.attestedNoDoubleBenefit) {
    rows.push(
      `# Attested no double benefit (not on Schedule A, not FSA/HRA reimbursed)${
        header.attestedAt ? ` at ${header.attestedAt}` : ""
      }`,
    );
  }
  rows.push(
    [
      "date_of_service",
      "patient",
      "vendor",
      "category",
      "amount_usd",
      "irs_pub_502_basis",
      "irs_pub_502_section",
      "reclaim_confirmation_timestamp",
      "document_count",
      "document_types",
    ]
      .map(csvEscape)
      .join(","),
  );
  for (const e of expenses) {
    rows.push(
      [
        e.date,
        e.patientName ?? "Self",
        e.vendor,
        e.category ?? "",
        e.amount.toFixed(2),
        e.ruleName ?? "",
        e.ruleSectionRef ?? "",
        e.confirmedAt,
        String(e.documents.length),
        e.documents.map(documentLabel).join("; "),
      ]
        .map((v) => csvEscape(String(v)))
        .join(","),
    );
  }
  return rows.join("\n");
}

// ── Browser download helper ──────────────────────────────────────────────

export function downloadBlob(filename: string, blob: Blob): void {
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  setTimeout(() => URL.revokeObjectURL(url), 5_000);
}
