-- Migration: Create inbox_items table for the Attention Queue (Phase 3)
-- Stores actionable items that need user attention, generated by triggers
-- on transactions and transaction_invoice_suggestions.

-- 1. Enum types
CREATE TYPE inbox_item_type AS ENUM (
  'review_transaction',   -- needs medical/non-medical classification
  'confirm_match'         -- Tier 2 suggested match needs one-click confirm
);

CREATE TYPE inbox_item_status AS ENUM ('pending', 'acted', 'dismissed', 'expired');

-- 2. Table
CREATE TABLE inbox_items (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  item_type inbox_item_type NOT NULL,

  -- Polymorphic reference to source entity
  source_entity_id UUID NOT NULL,
  source_entity_type TEXT NOT NULL,

  -- Precomputed display data (avoids JOINs for list rendering)
  title TEXT NOT NULL,
  subtitle TEXT,
  amount NUMERIC,
  suggested_action JSONB,

  priority_score INTEGER NOT NULL DEFAULT 50,
  status inbox_item_status NOT NULL DEFAULT 'pending',

  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  acted_at TIMESTAMPTZ,
  expires_at TIMESTAMPTZ,

  -- Prevent duplicate items for same source
  UNIQUE(user_id, source_entity_id, item_type)
);

-- 3. Indexes
CREATE INDEX idx_inbox_items_user_pending
  ON inbox_items(user_id, priority_score DESC)
  WHERE status = 'pending';
CREATE INDEX idx_inbox_items_source ON inbox_items(source_entity_id);

-- 4. RLS
ALTER TABLE inbox_items ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view their own inbox items"
  ON inbox_items FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can update their own inbox items"
  ON inbox_items FOR UPDATE USING (auth.uid() = user_id);
-- INSERT is open because SECURITY DEFINER trigger functions create these rows.
-- Triggers bypass RLS, but this policy covers edge cases where a direct insert is attempted.
CREATE POLICY "Users can insert their own inbox items"
  ON inbox_items FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can delete their own inbox items"
  ON inbox_items FOR DELETE USING (auth.uid() = user_id);

-- 5. Trigger: Generate review_transaction items when transactions are inserted with needs_review=true
CREATE OR REPLACE FUNCTION generate_review_inbox_item()
RETURNS TRIGGER AS $$
BEGIN
  IF NEW.needs_review = true THEN
    INSERT INTO inbox_items (user_id, item_type, source_entity_id, source_entity_type,
      title, subtitle, amount, priority_score)
    VALUES (
      NEW.user_id,
      'review_transaction',
      NEW.id,
      'transaction',
      COALESCE(NEW.vendor, NEW.description, 'Unknown Transaction'),
      'New transaction — is this medical?',
      NEW.amount,
      60
    )
    ON CONFLICT (user_id, source_entity_id, item_type) DO NOTHING;
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, pg_temp;

CREATE TRIGGER trg_inbox_review_transaction
  AFTER INSERT ON transactions
  FOR EACH ROW EXECUTE FUNCTION generate_review_inbox_item();

-- 6. Trigger: Generate confirm_match items for Tier 2 suggestions (0.7–0.9 confidence)
CREATE OR REPLACE FUNCTION generate_match_inbox_item()
RETURNS TRIGGER AS $$
DECLARE
  v_user_id UUID;
  v_txn_vendor TEXT;
  v_txn_amount NUMERIC;
  v_inv_vendor TEXT;
BEGIN
  IF NEW.confidence_score >= 0.7 AND NEW.confidence_score < 0.9 THEN
    SELECT t.user_id, COALESCE(t.vendor, t.description), t.amount
      INTO v_user_id, v_txn_vendor, v_txn_amount
      FROM transactions t WHERE t.id = NEW.transaction_id;

    SELECT i.vendor INTO v_inv_vendor
      FROM invoices i WHERE i.id = NEW.invoice_id;

    INSERT INTO inbox_items (user_id, item_type, source_entity_id, source_entity_type,
      title, subtitle, amount, suggested_action, priority_score)
    VALUES (
      v_user_id,
      'confirm_match',
      NEW.id,
      'transaction_invoice_suggestion',
      v_txn_vendor || ' → ' || v_inv_vendor,
      'Suggested match (' || ROUND(NEW.confidence_score * 100) || '% confidence)',
      v_txn_amount,
      jsonb_build_object(
        'action', 'link',
        'transaction_id', NEW.transaction_id,
        'invoice_id', NEW.invoice_id,
        'confidence', NEW.confidence_score
      ),
      80
    )
    ON CONFLICT (user_id, source_entity_id, item_type) DO NOTHING;
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, pg_temp;

CREATE TRIGGER trg_inbox_confirm_match
  AFTER INSERT ON transaction_invoice_suggestions
  FOR EACH ROW EXECUTE FUNCTION generate_match_inbox_item();

-- 7. Auto-resolve trigger: expire inbox items when transaction is linked or reviewed
CREATE OR REPLACE FUNCTION resolve_inbox_on_transaction_update()
RETURNS TRIGGER AS $$
BEGIN
  -- Transaction linked (status changed from unlinked)
  IF OLD.reconciliation_status = 'unlinked' AND NEW.reconciliation_status != 'unlinked' THEN
    UPDATE inbox_items
    SET status = 'expired', acted_at = now()
    WHERE source_entity_id = NEW.id
      AND source_entity_type = 'transaction'
      AND status = 'pending';
  END IF;

  -- Transaction reviewed (needs_review cleared)
  IF OLD.needs_review = true AND NEW.needs_review = false THEN
    UPDATE inbox_items
    SET status = 'expired', acted_at = now()
    WHERE source_entity_id = NEW.id
      AND source_entity_type = 'transaction'
      AND item_type = 'review_transaction'
      AND status = 'pending';
  END IF;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, pg_temp;

CREATE TRIGGER trg_resolve_inbox_on_transaction_update
  AFTER UPDATE ON transactions
  FOR EACH ROW EXECUTE FUNCTION resolve_inbox_on_transaction_update();

-- 8. Backfill: create inbox items for existing needs_review transactions
INSERT INTO inbox_items (user_id, item_type, source_entity_id, source_entity_type,
  title, subtitle, amount, priority_score)
SELECT
  t.user_id,
  'review_transaction',
  t.id,
  'transaction',
  COALESCE(t.vendor, t.description, 'Unknown Transaction'),
  'New transaction — is this medical?',
  t.amount,
  60
FROM transactions t
WHERE t.needs_review = true
  AND t.reconciliation_status = 'unlinked'
ON CONFLICT (user_id, source_entity_id, item_type) DO NOTHING;

COMMENT ON TABLE inbox_items IS 'Actionable attention queue items generated by triggers on transactions and match suggestions';
